# Generated by Django 5.0.1 on 2024-01-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nubank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "name",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name_plural": "Transaction Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="eventcategory",
            options={"verbose_name_plural": "Event Categories"},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nubank.transactioncategory",
            ),
        ),
    ]
